FROM php:8.3-cli-alpine

WORKDIR /var/www/html/backend

RUN apk add --no-cache \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libwebp-dev \
    postgresql-dev \
    sqlite-dev \
 && docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg \
    --with-webp \
 && docker-php-ext-install gd pdo pdo_pgsql pdo_sqlite

COPY . .

RUN chmod +x docker-entrypoint.sh

EXPOSE 8001

ENTRYPOINT ["./docker-entrypoint.sh"]
