FROM php:8.3-cli-alpine

WORKDIR /var/www/html/backend

RUN apk add --no-cache postgresql-dev sqlite-dev \
 && docker-php-ext-install pdo pdo_pgsql pdo_sqlite

COPY . .

RUN chmod +x docker-entrypoint.sh

EXPOSE 8001

ENTRYPOINT ["./docker-entrypoint.sh"]
