ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'COMMISSION_CONVERT_OUT';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'SHOPPING_WALLET_CONVERT_IN';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'CONVERT_FEE_DEBIT';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'WALLET_TRANSFER_OUT';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'WALLET_TRANSFER_IN';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'TRANSFER_FEE_DEBIT';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'TOPUP_CREDIT';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'ORDER_PURCHASE_DEBIT';

ALTER TYPE "WalletBalanceBucket" ADD VALUE IF NOT EXISTS 'SHOPPING';

ALTER TABLE "Wallet"
  ADD COLUMN IF NOT EXISTS "shoppingBalance" DECIMAL(18, 8) NOT NULL DEFAULT 0;

ALTER TABLE "WalletTransaction"
  ADD COLUMN IF NOT EXISTS "note" VARCHAR(255);

ALTER TABLE "Order"
  ADD COLUMN IF NOT EXISTS "walletAppliedUsdt" DECIMAL(18, 8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "cashDueUsdt" DECIMAL(18, 8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "cashPaymentMethod" VARCHAR(100);
