ALTER TYPE "CommissionType" ADD VALUE IF NOT EXISTS 'CASHBACK';

ALTER TYPE "CompanyBonusSourceType" ADD VALUE IF NOT EXISTS 'CASHBACK';

ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'CASHBACK_CREDIT';
