import {ReviewType} from './ReviewType';

export type ProductType = {
  id: number;
  packageId?: string;
  packageCode?: string;
  categoryCode?: string;
  categoryName?: string;
  supplierCode?: string;
  supplierName?: string;
  name: string;
  price: number;
  pv?: number;
  activeDays?: number;
  status?: string;
  itemCount?: number;
  shortDescription?: string;
  packageItems?: Array<{
    packageItemId: string;
    qty: number;
    productDetailId: string;
    productDetailCode: string;
    productDetailName: string;
    shortDescription?: string | null;
    description?: string | null;
    lineMemberPriceUsdt?: string;
    linePv?: string;
  }>;
  rating: number;
  ratingCount?: number;
  image: string;
  images: string[];
  sizes: string[];
  size: string;
  colors: any[];
  color: string;
  description: string;
  categories: string;
  is_bestseller: boolean;
  is_featured: boolean;
  is_out_of_stock: boolean;
  oldPrice?: number;
  quantity?: number;
  reviews: ReviewType[];
  types: string[];
  isNew: boolean;
  isTop: boolean;
  isFeatured: boolean;
  audience: string[];
  promotion: string;
  tags: string[];
};
