import {ReviewType} from './ReviewType';

export type ProductType = {
  id: number;
  productDetailId?: string;
  productCode?: string;
  categoryCode?: string;
  categoryName?: string;
  supplierCode?: string;
  supplierName?: string;
  name: string;
  price: number;
  pv?: number;
  dcwSpendEnabled?: boolean;
  dcwUsageAmount?: number;
  dcwRewardRate?: number;
  activeDays?: number;
  status?: string;
  itemCount?: number;
  shortDescription?: string;
  youtubeUrl?: string;
  rating: number;
  ratingCount?: number;
  image: string;
  images: string[];
  sizes: string[];
  size: string;
  colors: any[];
  color: string;
  description: string;
  categories: string;
  is_bestseller: boolean;
  is_featured: boolean;
  is_out_of_stock: boolean;
  oldPrice?: number;
  quantity?: number;
  reviews: ReviewType[];
  types: string[];
  isNew: boolean;
  isTop: boolean;
  isFeatured: boolean;
  audience: string[];
  promotion: string;
  tags: string[];
};
