ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'FIRM_REENTRY_CREDIT';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'FIRM_PRODUCT_DEBIT';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'FIRM_DCW_CREDIT';

ALTER TYPE "WalletBalanceBucket" ADD VALUE IF NOT EXISTS 'FIRM';

ALTER TABLE "Wallet"
ADD COLUMN IF NOT EXISTS "firmBalance" DECIMAL(18, 8) NOT NULL DEFAULT 0;
