server {
  listen 80 default_server;
  listen 443 ssl default_server;
  server_name _;

  ssl_certificate /etc/nginx/certs/origin.crt;
  ssl_certificate_key /etc/nginx/certs/origin.key;

  return 404;
}
